[tool.poetry]
repository = "https://github.com/TechnologyBrewery/krausening"

[project]
name = "krausening-cli"
version = "22.dev"
description = "Command-line utility to help use Krausening."
authors = [
    {name = "Chaoyi Sun"},
    {name = "Emily Wilkins"}
]
license = "MIT"
requires-python = ">=3.10"
dynamic = ["version", "dependencies"]
readme = "README.md"

keywords = ["properties", "configuration-management"]

[tool.poetry.dependencies]
krausening = {path = "../krausening-python", develop = true}
click = ">=8.2.1"

[project.scripts]
krausening = "krausening_cli.cli:krausening"

[tool.poetry.group.dev.dependencies]
behave = ">=1.2.6"
ruff = "^0.12.4"
kappa-maki = "^1.0.2"
assertpy = "^1.1"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"
